/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0.2/userguide/building_java_projects.html
 */

plugins {

    id("org.springframework.boot") version "2.5.0"
    id("io.spring.dependency-management") version "1.0.9.RELEASE"
    kotlin("plugin.spring") version "1.3.61"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}


val grpcVersion = "1.38.0"

group = "com.dailydesk.common-service-utils"

version = "0.0.1"
java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks.getByName<Jar>("bootJar") {
    enabled = false
}

 tasks.register<Exec>("local") {
   commandLine("echo", "common-service-utils!")
 }

tasks.getByName<Jar>("jar") {
//    duplicatesStrategy = DuplicatesStrategy.INCLUDE
//    metaInf{
//        from("src/main/resources/META-INF") {
//            include("**/*.factories")
//        }
//
//    }
    enabled = true
}


sourceSets {
    main {
        java {
            setSrcDirs(listOf("src/**"))
        }
    }
}

dependencies {
    implementation(project(":protobuf"))
    implementation(project(":common-bifrost-client"))

    implementation("io.grpc:grpc-netty-shaded:${grpcVersion}")


    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("org.apache.commons:commons-lang3:3.12.0")

    implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
    implementation("org.springframework.boot:spring-boot-starter-jersey")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.google.code.gson:gson:2.8.6")


    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:30.0-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")
}
