# restrict to changes to these domains
annotations:
    iam.amazonaws.com/role: arn:aws:iam::349142834852:user/kops
domainFilters:
  - godfall.dev.cluster.projctor.io
# descriptive text to show who created record
txtOwnerId: "externaldns"
aws:
  zoneType: public
  region: ""
# fetch latest image from the source
image:
  registry: registry.opensource.zalan.do
  repository: teapot/external-dns
  tag: latest